# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.56.99"
  config.vm.synced_folder "../.", "/var/www/za",
        owner: "www-data", group: "www-data"
  config.vm.provider "virtualbox" do |v|
    v.name = "za"
    v.memory = 512
    v.cpus = 1
  end
end
